language: php
php:
  - 5.6
  - 7.0
  - 7.1

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -u root --password="" test < tests/data/db.sql

addons:
apt:
  sources:
    - mysql-5.7-trusty
  packages:
    - mysql-server
    - mysql-client

# We don't want to run linux commands as super user
sudo: false

# Tell Travis CI to monitor only 'master' branch
branches:
only: master

install:
  composer install

script:
  - vendor/bin/phpunit
